### PR TITLE
46 assist level and start power boost now work as a factor of rider pedal human power

### PR DESCRIPTION
**Pull request by casainho**

### CODE REVIEW

**Comment by v-s-c-o-p-e** [comment]
I would put 

`    if (configuration_variables.ui8_startup_motor_power_boost_div25 > 0)
    if (configuration_variables.ui8_startup_motor_power_boost_assist_level > 0)
    {
      ui32_adc_max_battery_current_boost_state_x4 = (((uint32_t) configuration_variables.ui8_startup_motor_power_boost_div25) * 160) / ((uint32_t) ui16_battery_voltage_filtered);
      ui32_temp = (uint32_t) ui16_pedal_torque_x10 * (uint32_t) configuration_variables.ui8_startup_motor_power_boost_assist_level;
      ui32_temp /= 10;
      // 1.6 = 1 / 0.625 (each adc step for current)
      // 1.6 * 8 = ~13
      ui32_temp = (ui32_temp * 13) / ((uint32_t) ui16_battery_voltage_filtered);
      ui8_adc_max_battery_current_boost_state = ui32_temp >> 3;
      ui8_limit_max(&ui8_adc_max_battery_current_boost_state, 255);
    }`

after normal power calc since boost is always higher than normal power_cadence?

**Comment by lightcore-x** [comment]
@vscope Does it really matter? The normal power and boost power are calculated into separate variables. The order of calculation doesn't and shouldn't matter here?

**Comment by lightcore-x** [comment]
Issue #46
Will be tested before releasing version 0.15.0

**Comment by v-s-c-o-p-e** [comment]
yes! since if boost lags you still have normal cadence power!
so we do a check. only if boost / boostfade power > normal cadence power use power of boost.
quickfix (hack) for the boost lag problem.

**Comment by v-s-c-o-p-e** [comment]
hope you understand what i mean.

**Comment by v-s-c-o-p-e** [comment]
at the moment normal cadence is only calculated if (!ui8_boost_enabled_and_applied)
thats the reason the boost bug delivers 0 watts...

**Pull request merged**
