### PR TITLE
Fix the issue with no support when lights are on

### PR DESCRIPTION
**Pull request by djwlindenaar**
Implement the changes made in the 0.19.x branch again in the 0.20 branch

### CODE REVIEW

**Comment by djwlindenaar** [comment]
Same issue as: #71

**Comment by djwlindenaar** [comment]
I made a mistake in the math (although it was not noticeable while riding the bike), please disregard this pull request. I will submit a new one.

**Comment by djwlindenaar** [comment]
Fixed the mistake.

**Comment by casainho** [comment]
I accepted the #142 instead, that refers this PR of you. Thank you for your contribution.

**Pull request closed without merging**
