### PR TITLE
Candidate for version 0.17

### PR DESCRIPTION
**Pull request by leon927**
New source code with new functions and features.

Changes:
- Settable odometer
- Trip distance function
- Imperial units throughout the system
- Saved menu state for all menus when power down

### CODE REVIEW

**Comment by casainho** [comment]
I did a change to master as I told I would like to do and now are conflicts with this pull request. I guess will take me some time until I merge the changes... Hope to do it in 2 or 3 days max.

**Comment by leon927** [comment]
> I did a change to master as I told I would like to do and now are conflicts with this pull request. I guess will take me some time until I merge the changes... Hope to do it in 2 or 3 days max.

Yes, your code is really nice, well done!! 

I am sad we could not merge this pull request before your changes and together work to implement your code into my updates. It will take some time to merge and test now. Could you revert changes made to master? And step by step add your code into the updates? Maybe you find it easier to just merge the changes?

**Comment by casainho** [comment]
Temporary squash and merge -- needs work.

**Comment by casainho** [comment]
I did the merge but there are some issues to solve. I did a commit after solving some but there are more issues to solve, hopefully I will do it tomorrow.

**Pull request merged**
