### PR TITLE
Bug fixes and improvements

### PR DESCRIPTION
**Pull request by leon927**
Change log:

* No blinking 1 error anymore. Same safety logic is still there and even safer! Also, the safety logic has actually even expanded to include all motor operations so it protects the motor controller, blue gear and motor in every possible use case/situation.
* New function has been created that replaces safe_tests(). The new function is called check_system.
* Firmware is also prepared for more error codes in the future as Casainho has given feedback about this.
* Slightly tuned the controller for the cruise function so it should work better for both motors.
* Solved unknown bug in the UART communication making it at at least two times faster.
* The UART communication has been cleaned up and is easier to change for future displays. Easier to add data for communication without changing a lot of parameters in several different places in the code.
* Overall clean up in the KT-LCD3 firmware and solved bugs. New button logic is fixed and improved a lot.
* And other things...

### CODE REVIEW

**Comment by leon927** [comment]
**Casainho, If everything works and there are no new changes after the new beta I wrote this for the stable release notes. You can change it if you want but just wanted to help because I had the complete list on hand.**

Description:
-----------------------
This is the release of the stable version 0.19.0 of the Open Source TSDZ2 firmware. Below is the entire changelog from version 0.18.X.

See the official Endless Sphere [thread](https://endless-sphere.com/forums/viewtopic.php?f=30&t=93818&start=1700) for more information and relevant discussion.

See the [wiki](https://github.com/OpenSource-EBike-firmware/TSDZ2_wiki/wiki/Features-and-configurations-for-version-0.19.X) for information regarding operation and configuration of the KT-LCD3 and the TSDZ2.


Changelog
-----------------------
* Solved motor backwards resistance
* Corrected cadence value and human power
* Throttle now overrides torque sensor
* Improved BOOST code in the hope to solve a bug related to BOOST
* Added estimated range since power on depending on how much capacity is left
* Added option to set motor power limit in the configuration menu
* Added option to enable or disable motor power limit quick-set-menu
* Added two new main screen setup items
* More accurate watt-hour measurement
* More accurate time measurement
* Heavily optimized code size and speed
* Safer enable logic for Walk Assist and Cruise
* Added average wheel speed in temperature field
* More modular uart for future displays
* New button logic and completely new setup menu
* Solved unknown bug in UART communication making it at at least two times faster
* Tuned the controller for the cruise function so that is works okay for both motors
* New system safe test function
* Added a function that measures and calculates consumed watt-hours per traveled distance since power on
* Added a new sub field in the odometer field temporarily called Energy where user will see energy consumption and estimated range
* Merged previous configuration menu LCD Setup with configuration menu General Setup for better and faster setup
* Removed configuration menu LCD Setup
* Merged all battery setup menus to one
* Added option that enables user to enable or disable display of motor temperature in the odometer field
* Changed order in the Main Screen Setup menu in the configuration menu
* Changed order in the odometer field
* Improved pedal cadence calculation
* Updated README document
* Overall optimizations in regard to size and speed
* Cleaned up code and comments
* Created [wiki](https://github.com/OpenSource-EBike-firmware/TSDZ2_wiki/wiki/0.19.0-(BETA)) that has been updated with all the changes
* And more...


Links:
-----------------------
**Wiki:**
https://github.com/OpenSource-EBike-firmware/TSDZ2_wiki/wiki/Features-and-configurations-for-version-0.19.X

**Endless Sphere thread:**
https://endless-sphere.com/forums/viewtopic.php?f=30&t=93818&start=1700

**Review by casainho — CHANGES_REQUESTED** [review]
SVM stands for Space Vector Modulation, which is correct name because the numbers there are for SVM and note sine. At begin of the project I tested Sine values but motor were a bit more noiser and took a bit more current. SVM seems the best to use when reading the literature.
Can you please correct the name of that array?

**Comment by leon927** [comment]
I have not made changes in the motor code in the past (besides this small change now) but would love to do future development. Such as Field weakening #11. We can maybe start a discussion in the future about this as I would love to hear your input. 

But for now: I remembered this in the thread on page 61 and thought it would be good to change it as the array length should be shorter:

Link to thread page: 
https://endless-sphere.com/forums/viewtopic.php?f=30&t=93818&p=1436303#p1436303



marcoq post_id=1436303 time=1546635052 user_id=62585
Hello casainho.
In the motor.c file at line 290 I noticed that **ui8_sin_table** has a length of 256 **SVM_TABLE_LEN** ... it should not be long 60 **SIN_TABLE_LEN**?
Thanks, have a good day.
[/quote]

casainho post_id=1436240 time=1546620272 user_id=18879
Yes, probably.

------------------------

Am open to change the name of the table but just need to confirm what you want to change. This is the code now:

#define SVM_TABLE_LEN   256
#define SIN_TABLE_LEN   60

uint8_t ui8_svm_table [SVM_TABLE_LEN] =
{
    239 ,
    241 ,
... ... ... ...
    239 ,
    238 ,
};

uint8_t ui8_sin_table [SIN_TABLE_LEN] =
{
    0 ,
    3 ,
... ... ... ...
    126 ,
    127
};

------------------------

This is the "old" code before my change:

#define SVM_TABLE_LEN   256
#define SIN_TABLE_LEN   60

uint8_t ui8_svm_table [SVM_TABLE_LEN] =
{
    239 ,
    241 ,
... ... ... ...
    239 ,
    238 ,
};

uint8_t ui8_sin_table [SVM_TABLE_LEN] =
{
    0 ,
    3 ,
... ... ... ...
    126 ,
    127
};

------------------------

Only the SVM_TABLE_LEN was changed to SIN_TABLE_LEN to make the array declaration the correct size/length/LEN of **ui8_sin_table** .

**Comment by casainho** [comment]
Ok I see now, you are correct and that table/array is being used only here:

// calc asin also converts the final result to degrees
uint8_t asin_table (uint8_t ui8_inverted_angle_x128)

And yes, the size of array is 60.

I though you were just renaming the arrays.

**Comment by casainho** [comment]
Should I make a beta version??

**Comment by leon927** [comment]
Thank you for asking! Yes if you wish to so people can start reporting the remaining bugs! :)

**Comment by djwlindenaar** [comment]
That'd be great. I'll test it, but haven't been able to build the LCD code myself

**Pull request merged**
