### PR TITLE
Fixed bugs and added time measurement 

### PR DESCRIPTION
**Pull request by leon927**

### CODE REVIEW

**Comment by leon927** [comment]
I have not changed any function or anything in the controller code. Just made small changes to comments and tried to make the code easier to understand for debugging the calculation for human power.

The code in the controller is not any different in functionality and is fully compatible with everything else: v0.16, v0.17 and all betas.

**Comment by casainho** [comment]
I am getting this issue when building:

_sdcc -c -I../../common/STM8S_StdPeriph_Lib/inc -I. -I../../ -mstm8 -Ddouble=float --std-c99 --nolospre --out-fmt-elf --debug  -olcd.c lcd.c
lcd.asm:12839: Error: <r> relocation error
Segmentation fault (core dumped)
Makefile_linux:73: recipe for target 'lcd.rel' failed_

**Comment by casainho** [comment]
Ok, I corrected it. Which version of SDCC are you using?? I can't assign a value to a static variable otherwise I get that error.

**Comment by leon927** [comment]
> 
> 
> Ok, I corrected it. Which version of SDCC are you using?? I can't assign a value to a static variable otherwise I get that error.

I am using 3.8.0. I had no errors building the code. Is there something I need to think about for future development?

**Comment by leon927** [comment]
I just saw how you corrected the error. I initialized a static variable to "0" inside a function. That is unnecessary. A static will always initialize to 0 but I added it for clarity and because I had no errors in my SDCC.

**Comment by casainho** [comment]
> Is there something I need to think about for future development?
Yes, please this:
1. https://github.com/OpenSource-EBike-firmware/TSDZ2-Smart-EBike/issues/55
2. LCD configuration of current ramp (maybe configure on LCD amps per second of the ramp):
// Target: ramp 5 amps per second
// every second has 15625 PWM cycles interrupts
// 1 ADC battery current step --> 0.625 amps
// 5 / 0.625 = 8 (we need to do 8 steps ramp up per second)
// 15625 / 8 = 1953
#define ADC_BATTERY_CURRENT_RAMP_UP_INVERSE_STEP 1953

**Pull request merged**
