### PR TITLE
Minimal motor current

### PR DESCRIPTION
**Pull request by bbeschea**
> I would add a min value of motor current, near the final sequence of motor current that is calculated on ebike_control_motor(). The min motor current should be a fixed value that do not depends of pedal torque and cadence.
> 
> casainho

I added only 1 unit. should be enough.

### CODE REVIEW

**Comment by casainho** [comment]
Seems good but please see my comment on the code. I suggest you to now created HEX files and share on forum for others to test.

**Comment by bbeschea** [comment]
I did the changes now because I had a bit of spare time at work. I do not have the STM software installed here so I cannot make the binaries. I can do it in the evening.
I do not see any comments on this pull request on the code from you... please explain.
If the code is ok can you merge it to main project?

**Comment by casainho** [comment]
My comment: MIN_BATTERY_CURRENT must be instead MIN_ADC_BATTERY_CURRENT.

I think Jabalat can try this (build and test the code), maybe you should pass the link to him.

**Comment by lightcore-x** [comment]
Thanks bbschea!

> If the code is ok can you merge it to main project?

No, not yet. We should thoroughly test it first. When necessary we can create a beta release for other users to test. Did you test this?

**Comment by bbeschea** [comment]
Change done. I will let Jbalat know.

**Comment by bbeschea** [comment]
I double checked the change and it makes sense. The current is added checked by temp function and then is used. Jbalat and other user still reported lag...
I saw that all the logic in ebike module is called in main.c in while loop.
Is is possbile that there are some delays from that loop and the program counter cannot get to the current  adding code in time? 
Can you somehow debug this flow and check the loop time execution?

**Comment by bbeschea** [comment]
At the moment I see no need to keep this pull request. If you think the same, I can close it.

**Pull request closed without merging**
